### PR TITLE
Resolves #11: Take the colorScheme from the system automatically

### LINKED ISSUE #11: By default, it should adapt to the system's colorScheme setting
Right now, `.light`is used as the default `colorScheme`. Instead, the `colorScheme` should be taken from the system's `colorScheme` setting. Otherwise, when using the library, you have to make sure that Neumorphic's `colorScheme` updates with the system's `colorScheme` manually.

`@Environment(\.colorScheme)` can be used for that.

### PR DESCRIPTION
**Pull request by dkk**
The colorScheme is now automatically set correctly (without having to explicitly update it with `Neumorphic.shared.colorScheme = colorScheme`)

I also took the oportunity to remove the Neumorphic singleton which was not really needed. Neumorphic's colors can now be accessed through `Color.Neumorphic`, since I moved them to a Color extension.

I also did some minor cleanup in SoftSwitchToggleDemoView.swift's preview

Note that if you merge this PR the next version should be 2.0.0 since it contains breaking changes.

### CODE REVIEW

**Comment by costachung** [comment]
Thanks for your contribution! I have reviewed the changes you made and I love it very much. Using Color extension to access neumorphic default colors makes more sense and it makes code much cleaner.

**Review by costachung — COMMENTED** [review]
Using Color extension to access neumorphic default colors makes more sense and it makes code much cleaner.

**Comment by costachung** [comment]
@dkk We should use Color instead of UIColor in the new color extension so that it will work on both MacOS and iOS.

**Comment by dkk** [comment]
Unfortunatelly, after a bit of research, it seems that the only way to support iOS and OSX colors with a dark version would be to go back to the singleton. The reason being that neither NSColor nor Color support programatically setting light & dark versions of a color simultaneously. 

There also seems to be no way of deploying a color xcasset in a way that the SPM uses it correctly, at least I had no luck, even using workarounds like https://developer.apple.com/forums/thread/664295.

**Comment by dkk** [comment]
well, maybe not a singleton. Probably an instance using the colorScheme Environment var will be enough.

**Comment by costachung** [comment]
We do not need to go back to the singleton way. I think we can use take a different approach for macOS to detect the dark mode. I have update the code in master. please check it out. If it looks good, we can make a new release on that.

**Comment by costachung** [comment]
I also added an example project for Mac. You may have a look.

**Comment by costachung** [comment]
I made a new release anyway so that you can test it.
https://github.com/costachung/neumorphic/releases/tag/v2.0.1

**Comment by costachung** [comment]
https://github.com/costachung/neumorphic/issues/13

**Comment by dkk** [comment]
looks good, could be refactored a bit though.. for instance there are some private unused colors.

**Comment by dkk** [comment]
(Refactoring PR #14 )

**Pull request merged**
